# Python Experiment No: 11

Name: Madhav Prakash Pachakale.

Class: SE3/S3/65

In [3]:
import numpy as np

print("Name: Madhav Prakash Pachakale.   Class: SE3/S3/65")
print("1. Array Creation Techniques")

array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

array_arange = np.arange(0, 10, 2)
print("Array using arange():", array_arange)

array_linspace = np.linspace(0, 10, 5)
print("Array using linspace():", array_linspace)

array_zeros = np.zeros((3, 3))
print("Array using zeros():\n", array_zeros)

array_ones = np.ones((2, 2))
print("Array using ones():\n", array_ones)

array_eye = np.eye(3)
print("Array using eye() for identity matrix:\n", array_eye)

array_random = np.random.random((3, 3))
print("Array using random():\n", array_random)

print("\n2. NumPy Methods")

reshaped_array = np.arange(1, 10).reshape(3, 3)
print("Reshaped array:\n", reshaped_array)

transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

array_math = np.array([1, 2, 3])
print("Array + 2:", array_math + 2)
print("Array * 3:", array_math * 3)
print("Square root of array:", np.sqrt(array_math))

print("Sum of array:", np.sum(array_math))
print("Mean of array:", np.mean(array_math))
print("Max of array:", np.max(array_math))
print("Min of array:", np.min(array_math))

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concat_array = np.concatenate((array_a, array_b))
print("Concatenated array:", concat_array)

unsorted_array = np.array([3, 1, 4, 2])
sorted_array = np.sort(unsorted_array)
print("Sorted array:", sorted_array)

indexed_value = array_math[1]
print("Indexed value (array_math[1]):", indexed_value)
sliced_array = array_math[1:3]
print("Sliced array (array_math[1:3]):", sliced_array)

boolean_mask = array_math > 2
print("Boolean mask (array_math > 2):", boolean_mask)
print("Array values with boolean mask:", array_math[boolean_mask])


Name: Madhav Prakash Pachakale.   Class: SE3/S3/65
1. Array Creation Techniques
Array from list: [1 2 3 4 5]
Array using arange(): [0 2 4 6 8]
Array using linspace(): [ 0.   2.5  5.   7.5 10. ]
Array using zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array using ones():
 [[1. 1.]
 [1. 1.]]
Array using eye() for identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array using random():
 [[0.89445287 0.73131026 0.18389612]
 [0.38141738 0.58245741 0.44130747]
 [0.68147723 0.35550251 0.76976466]]

2. NumPy Methods
Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Array + 2: [3 4 5]
Array * 3: [3 6 9]
Square root of array: [1.         1.41421356 1.73205081]
Sum of array: 6
Mean of array: 2.0
Max of array: 3
Min of array: 1
Concatenated array: [1 2 3 4 5 6]
Sorted array: [1 2 3 4]
Indexed value (array_math[1]): 2
Sliced array (array_math[1:3]): [2 3]
Boolean mask (array_math > 2): [False False  True]
Array values with boolean mask: [3]
